In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time

In [2]:
# Calling the .csv file with stastical features

In [3]:
features_data = pd.read_csv('C:/Users/intel/Desktop/Mtech_Proj/Digital twin_29 Jan 2021/Low_features_digitalTwin_fault.csv',
                            index_col=0)

In [4]:
# Test Train split 30%

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = features_data.drop('fault_Class',axis=1)
y = features_data['fault_Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [7]:
X_train

x_Mean     x_Min  x_Kurtosis  x_Crest_Factor  x_Skewness  \
1055 -0.020383 -0.586491    1.677786        4.523080   -0.298658   
569  -0.013089 -0.580244    1.680595        4.400976   -0.138859   
4847 -0.015911 -0.580244    1.790892        4.321216   -0.131466   
8007  0.581752 -0.727554   -0.445078        3.268655    0.902331   
4792 -0.017505 -0.629895    2.198723        3.929555   -0.146240   
...        ...       ...         ...             ...         ...   
8584  0.592858 -0.601288    0.362306        3.582259    1.058302   
1575 -0.019218 -0.593397    1.056789        4.190649   -0.222756   
560  -0.019059 -0.579257    1.697746        4.074303   -0.142184   
4170 -0.017922 -0.672971    2.081132        3.687837   -0.149609   
277  -0.014288 -0.686123    1.792196        3.930484   -0.127895   

      x_Form_Factor  
1055      -6.143098  
569       -9.494941  
4847      -7.974150  
8007       1.459694  
4792      -7.530504  
...             ...  
8584       1.480517  
1575      -6.215754  
560       -6.797819  
4170      -7.379848  
277       -9.054073  

[6160 rows x 6 columns]

In [8]:
# perform standard scalar normalization to normalize our feature set

In [9]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Applying PCA

In [11]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [13]:
# Performance Evaluation

In [14]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[353   3 153   1   0]
 [  0 541   0   0   0]
 [125   0 404   0   0]
 [  0   0   0 521   0]
 [  0   0   0   0 539]]
              precision    recall  f1-score   support

          C1       0.74      0.69      0.71       510
          C2       0.99      1.00      1.00       541
          C3       0.73      0.76      0.74       529
          C4       1.00      1.00      1.00       521
          C5       1.00      1.00      1.00       539

    accuracy                           0.89      2640
   macro avg       0.89      0.89      0.89      2640
weighted avg       0.89      0.89      0.89      2640



In [15]:
# Results with 2 or 3 Principal Components

In [16]:
pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [17]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[312   3 194   1   0]
 [  0 541   0   0   0]
 [121   0 408   0   0]
 [  0   0   0 521   0]
 [  0   0   0   0 539]]
              precision    recall  f1-score   support

          C1       0.72      0.61      0.66       510
          C2       0.99      1.00      1.00       541
          C3       0.68      0.77      0.72       529
          C4       1.00      1.00      1.00       521
          C5       1.00      1.00      1.00       539

    accuracy                           0.88      2640
   macro avg       0.88      0.88      0.88      2640
weighted avg       0.88      0.88      0.88      2640

