In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time

In [2]:
features_data = pd.read_csv('features_digitalTwin_fault.csv',index_col=0)

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = features_data.drop('fault_Class',axis=1)
y = features_data['fault_Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [5]:
from sklearn.svm import SVC

In [6]:
svc_model = SVC()

In [7]:
start = time.time()
svc_model.fit(X_train,y_train)
stop = time.time()
print(f"Training time: {stop - start}s")


Training time: 0.3749666213989258s


In [8]:
predictions = svc_model.predict(X_test)

In [9]:
from sklearn.metrics import classification_report,confusion_matrix

In [10]:
print(confusion_matrix(y_test,predictions))

[[237  25   0   0   0   0]
 [ 82 176   0   6   0   0]
 [  0   0 269   0   0   0]
 [  0   2   0 272   0   0]
 [  0   0   0   1 257   0]
 [  0   0   1   1   1 254]]


In [11]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          C1       0.74      0.90      0.82       262
          C2       0.87      0.67      0.75       264
          C3       1.00      1.00      1.00       269
          C4       0.97      0.99      0.98       274
          C5       1.00      1.00      1.00       258
          C6       1.00      0.99      0.99       257

    accuracy                           0.92      1584
   macro avg       0.93      0.92      0.92      1584
weighted avg       0.93      0.92      0.92      1584



In [12]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]} 
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................... C=0.1, gamma=1, total=   0.9s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s


[CV] ................................... C=0.1, gamma=1, total=   0.9s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.9s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.9s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.9s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.5s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.5s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .

[CV] ................................... C=100, gamma=1, total=   0.7s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.7s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.7s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.7s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.7s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.4s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.4s
[CV] C=100, gamma=0.1 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:   31.4s finished


[[234  28   0   0   0   0]
 [ 44 217   0   2   0   1]
 [  0   0 269   0   0   0]
 [  0   0   0 274   0   0]
 [  0   0   0   0 257   1]
 [  0   0   0   0   0 257]]


In [13]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

          C1       0.84      0.89      0.87       262
          C2       0.89      0.82      0.85       264
          C3       1.00      1.00      1.00       269
          C4       0.99      1.00      1.00       274
          C5       1.00      1.00      1.00       258
          C6       0.99      1.00      1.00       257

    accuracy                           0.95      1584
   macro avg       0.95      0.95      0.95      1584
weighted avg       0.95      0.95      0.95      1584

