In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time

Calling the .csv file with stastical features

In [2]:
features_data = pd.read_csv('C:/Users/intel/Desktop/Mtech_Proj/Digital twin_29 Jan 2021/Low_features_digitalTwin_fault.csv',index_col=0)

Test Train split 30%

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
X = features_data.drop('fault_Class',axis=1)
y = features_data['fault_Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [6]:
from sklearn.svm import SVC
svc_model = SVC()

In [16]:
start = time.time()
svc_model.fit(X_train,y_train)
stop = time.time()
print(f"Training time: {stop - start}s")


Training time: 0.21875286102294922s


In [8]:
predictions = svc_model.predict(X_test)

In [9]:
from sklearn.metrics import classification_report,confusion_matrix

In [10]:
print(confusion_matrix(y_test,predictions))

[[418   0 111   0   0]
 [  0 519   0   0   0]
 [115   0 409   0   0]
 [  0   0   0 546   0]
 [  0   0   0   0 522]]


In [11]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          C1       0.78      0.79      0.79       529
          C2       1.00      1.00      1.00       519
          C3       0.79      0.78      0.78       524
          C4       1.00      1.00      1.00       546
          C5       1.00      1.00      1.00       522

    accuracy                           0.91      2640
   macro avg       0.91      0.91      0.91      2640
weighted avg       0.91      0.91      0.91      2640



### Grid SearchCV optimisation

In [24]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]} 
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
start = time.time()
grid.fit(X_train,y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................... C=0.1, gamma=1, total=   0.3s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s


[CV] ................................... C=0.1, gamma=1, total=   0.3s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.3s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.3s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.3s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.2s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.3s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.3s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .

[CV] ................................ C=10, gamma=0.001, total=   0.3s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.5s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.6s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.6s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.9s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.8s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.3s
[CV] C=100, gamma=0.1 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:   28.2s finished


Training time: 28.5595703125s
[[425   0 104   0   0]
 [  0 519   0   0   0]
 [125   0 399   0   0]
 [  0   0   0 546   0]
 [  0   0   0   0 522]]


In [45]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

          C1       0.81      0.80      0.81       563
          C2       1.00      1.00      1.00       505
          C3       0.80      0.81      0.80       539
          C4       1.00      1.00      1.00       540
          C5       1.00      1.00      1.00       493

    accuracy                           0.92      2640
   macro avg       0.92      0.92      0.92      2640
weighted avg       0.92      0.92      0.92      2640



### Polynomial Kernel Optimisation

In [17]:
# from sklearn.svm import SVC
start = time.time()
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

Training time: 64.14122939109802s


In [18]:
y_pred = svclassifier.predict(X_test)

In [19]:
# from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[451   0  59   7   0]
 [  0   0   0 530   0]
 [190   0 356   1   0]
 [  0   0   0 505   0]
 [  0   0   0 541   0]]
              precision    recall  f1-score   support

          C1       0.70      0.87      0.78       517
          C2       0.00      0.00      0.00       530
          C3       0.86      0.65      0.74       547
          C4       0.32      1.00      0.48       505
          C5       0.00      0.00      0.00       541

    accuracy                           0.50      2640
   macro avg       0.38      0.50      0.40      2640
weighted avg       0.38      0.50      0.40      2640



C:\Users\intel\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gaussian Kernel

In [17]:
svclassifier = SVC(kernel='rbf')
start = time.time()
svclassifier.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Training time: 0.2031264305114746s
[[418   0 111   0   0]
 [  0 519   0   0   0]
 [115   0 409   0   0]
 [  0   0   0 546   0]
 [  0   0   0   0 522]]
              precision    recall  f1-score   support

          C1       0.78      0.79      0.79       529
          C2       1.00      1.00      1.00       519
          C3       0.79      0.78      0.78       524
          C4       1.00      1.00      1.00       546
          C5       1.00      1.00      1.00       522

    accuracy                           0.91      2640
   macro avg       0.91      0.91      0.91      2640
weighted avg       0.91      0.91      0.91      2640



### Sigmoid Kernel-- Suited for binary classifications only

In [21]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[301   2 213   1   0]
 [  0 530   0   0   0]
 [237   0 310   0   0]
 [  0   0   0 505   0]
 [  0   0   0   0 541]]
              precision    recall  f1-score   support

          C1       0.56      0.58      0.57       517
          C2       1.00      1.00      1.00       530
          C3       0.59      0.57      0.58       547
          C4       1.00      1.00      1.00       505
          C5       1.00      1.00      1.00       541

    accuracy                           0.83      2640
   macro avg       0.83      0.83      0.83      2640
weighted avg       0.83      0.83      0.83      2640



### Naive Bayes classifier

In [20]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
y_pred = gnb.predict(X_test)   

In [21]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[325   0 204   0   0]
 [  0 519   0   0   0]
 [ 77   0 447   0   0]
 [  0   0   0 546   0]
 [  0   0   0   0 522]]
              precision    recall  f1-score   support

          C1       0.81      0.61      0.70       529
          C2       1.00      1.00      1.00       519
          C3       0.69      0.85      0.76       524
          C4       1.00      1.00      1.00       546
          C5       1.00      1.00      1.00       522

    accuracy                           0.89      2640
   macro avg       0.90      0.89      0.89      2640
weighted avg       0.90      0.89      0.89      2640

